---
name: Catalyst-Request-REST-ForBrowsers
version: 0.03
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: A Catalyst::Request::REST subclass for dealing with browsers
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTTP::Headers: 0
  Test::More: 0
requires:
  Catalyst::Action::REST: 0.41
  Moose: 0
configure_requires:
  Module::Build: 0.35
provides:
  Catalyst::Request::REST::ForBrowsers:
    file: lib/Catalyst/Request/REST/ForBrowsers.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
